### ISSUE TITLE
Can't intall radeon pro render: libGL.so not found

### ISSUE THREAD

**Issue by MrPixel1** [flathub/org.blender.Blender#132]
Installing the addon from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases (I used 3.5.0 with Blender version 3.4.1) causes the following error:
```
Traceback (most recent call last):
  File "/app/blender/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/user/.var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/__init__.py", line 52, in <module>
    from .engine.viewport_engine import ViewportEngine
  File "/home/user/.var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/engine/viewport_engine.py", line 32, in <module>
    from rprblender.utils import gl
  File "/home/user/.var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/app/blender/3.4/python/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/app/blender/3.4/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory
```

The default permissions look fine though:
```
$ flatpak info --show-permissions org.blender.Blender
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;fallback-x11;
devices=dri;
filesystems=/run/spnav.sock:ro;host;

[Environment]
SPNAV_SOCKET=/run/spnav.sock
TMP_DIR=/tmp
TMP=/tmp
```

**Comment by kevinsmia1939** [comment]
Any graphics card you are using?

**Comment by MrPixel1** [comment]
Yes, an AMD RX 5700 XT. It‘s being used correctly in other flatpaks.

**Comment by superuser-miguel** [comment]
Just out of curiosity @MrPixel1 Did you follow these instructions too? 

https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/installation.html
