### ISSUE TITLE
no OpenCL

### ISSUE THREAD

**Issue by mikelpr** [flathub/org.blender.Blender#26]
(#8 but in oss)

**Comment by bochecha** [comment]
Hi, before I can work on this I'll need a way to test this.

How can I see whether OpenCL is enabled or not in Blender?

**Comment by mikelpr** [comment]
Edit -> Preferences -> System
https://imgur.com/BiFeXI5

I think it's a flatpak/freedesktop runtime limitation atm, I just reported it here so it's kept in mind when it eventually is solved in the fdo runtime or as an extension so we get it rebuilt

**Comment by mikelpr** [comment]
[seems it was already solved there though](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/333)

**Comment by maddovr** [comment]
Is there still something blocking this?

**Comment by bochecha** [comment]
> Is there still something blocking this?

Well, I still don't know how to have Blender pick it up.

As @mikelpr said the FDO SDK did its part, but that still doesn't work so something must be needed in the Blender build as well.

Maybe I need to add a dependency? Maybe a platform extension is needed? Is it something like CUDA which requires specific hardware?

I need help from somebody who knows how OpenCL works and how to make it work. Do you? :slightly_smiling_face:

**Comment by maddovr** [comment]
Unfortunately I do not know much of how OpenCL work sorry. Maybe try to reach blender devs on freenode #blender ?

**Comment by jjardon** [comment]
@bochecha I think this link can help: https://wiki.archlinux.org/index.php/GPGPU

So you need different software depending on your hardware:
- Intel: intel-compute-runtime, beignet (for old hardware)
- nvidia: cuda
- amd: opencl from mesa (this is the only one supported in fdsdk at the moment)

**Comment by bochecha** [comment]
Thanks @jjardon 

> @bochecha I think this link can help: https://wiki.archlinux.org/index.php/GPGPU
> 
> So you need different software depending on your hardware:
> 
>     * Intel: intel-compute-runtime, beignet (for old hardware)
> 
>     * nvidia: cuda

We have #8 where this is tracked.

>     * amd: opencl from mesa (this is the only one supported in fdsdk at the moment)

Ah, so opencl is only for AMD? No wonder I can't test/reproduce this. :laughing: 

So, does anybody have AMD hardware to test whether this is fixed now that we are running on 18.08 which includes opencl?

**Comment by maddovr** [comment]
Technically, intel should work as well since it's mesa, but I can prove it doesn't get recognized on my intel iGPU.

**Comment by arpu** [comment]
tested with latest stable releases works with the blender bin from homepage 
![Bildschirmfoto von 2020-06-15 15-56-53](https://user-images.githubusercontent.com/14173/84666069-ebe9be00-af20-11ea-97b9-2f6e3f15fcfd.png)

but not with he flathub installed Blender 2.83.0

**Comment by manzyun** [comment]
Excuse me. I too have encountered the events in this thread.

However, I may be doing things differently than the rest of you. Hence, I'm sorry if I've caused confusion in the discussion.

The way I got to enable OpenCL rendering was to "install the AMD Radeon ProRender plugin", so I downloaded the ProRender plugin from [AMD's official web page](https://www.amd.com/en/technologies/radeon-prorender-downloads) and installed it on my installed Blender using FlatHub.

But when I activated it, I got the following error message and stack trace.

```
Traceback (most recent call last):
  File "/app/share/blender/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/manzyun/.var/app/org.blender.Blender/config/blender/2.83/scripts/addons/rprblender/__init__.py", line 50, in <module>
    from .engine.viewport_engine import ViewportEngine, ViewportEngine2
  File "/home/manzyun/.var/app/org.blender.Blender/config/blender/2.83/scripts/addons/rprblender/engine/viewport_engine.py", line 31, in <module>
    from rprblender.utils import gl
  File "/home/manzyun/.var/app/org.blender.Blender/config/blender/2.83/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory
```

It's my foolish opinion that I'm just missing something in the package I have installed on my machine, and it may not be enough to post here, but I hope it's helpful.

<details>
<summary>My machine spec</summary>

```
$ neofetch
            .-/+oossssoo+/-.               manzyun@my-machine
        `:+ssssssssssssssssss+:`           ----------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MS-7693 4.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-40-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 hours, 5 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2685 (dpkg), 95 (flatpak), 15 (sn 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: fish 3.1.0 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3840x2160 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD FX-8320E (8) @ 3.200GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI Radeon R7 370 / R9 270/370 OEM 
      -+sssssssssssssssssyyyssss+-         GPU: AMD ATI Radeon R7 370 / R9 270/370 OEM 
        `:+ssssssssssssssssss+:`           Memory: 6955MiB / 32063MiB 
            .-/+oossssoo+/-.
```

</details>

**Comment by zicklag** [comment]
With the latest release of the flatpak it is downloading binary releases of Blender so the stuff necessary for OpenCL should be included I think. It fixed CUDA for me so try it out and see if it works!

**Comment by manzyun** [comment]
@plafue Appreciate mention for me 🙇🏼 

> Did you have the time to check if opencl works for you? Could you try with the latest flatpak version?

Yes. flatpak version is latest from repository on [Launchpad](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak). 
I was tried select OpenCL in `Preference > System > Cycles Rendering`.

...Oops, `AMD ATI Radeon R7 370` is less than GCN 2, isn't it ?

Before that, I've been feeling lately that my knowledge of my own hardware configuration is questionable, despite the fact that I built the machine myself.

I apologize for the inconvenience. Thanks.

**Comment by plafue** [comment]
@manzyun thanks for the quick reply!

@mikelpr could you please give the current flatpak version a go?

**Comment by amzamora** [comment]
I don't know if this useful, but I just tried to get OpenCL working on elementary os 6 with a AMD RX 580 and didn't work. Although it works with Blender downloaded from the main site. 

Blender from flathub
![Captura realizada el 2021-09-01 23 23 35](https://user-images.githubusercontent.com/11808513/131776853-291a0d3e-a1f6-4ff0-9b88-124a8e3b899a.png)

Blender from the main site
![Captura realizada el 2021-09-01 23 24 02](https://user-images.githubusercontent.com/11808513/131776994-533c2a41-ca50-4846-8790-248a692af3e0.png)

(Also I enabled gpu acceleration for the flathub version. Don't know if this was necessary or there is something else that is needed)

**Comment by kevinsmia1939** [comment]
Consider that Blender 3.0 will have AMD GPU support as one of the big feature, we should figure something out, but it will use HIP and not OpenCL.

**Comment by mamoit** [comment]
Blender 3.0 is here :tada:
If I'm not mistaken, currently there is no HIP support right?
What changes would be needed?

**Comment by fastoslinux** [comment]
Any news about HIP support? currently the flatpak blender does not "see" the system's rocm-hip..

**Comment by orowith2os** [comment]
We can't do much, unless you're willing to fund the relevant (interested) people to be able to actually *build* the HIP libraries and put in the effort to make them work properly within a Flatpak environment.
